### ISSUE TITLE
[2.2.0]Impossible to install a new database

### ISSUE THREAD

**Issue by flotho** [OCA/connector#111]
Hi everyone,

I know that the 2.2.0 is an old tag and the API has been refarctored.
Yet this tag seems to be the one used for https://github.com/OCA/connector-prestashop/pull/11
So I use it and try to create a new database and it failed.
I have two issues :

```
2015-08-22 18:28:26,929 2061 DEBUG ? openerp.http: Loading sale_payment_method_automatic_workflow
2015-08-22 18:28:26,933 2061 DEBUG ? openerp.http: Loading prestashoperpconnect
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/worker.py", line 313, in run
    self._update_workers()
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/worker.py", line 301, in _update_workers
    db_names = self.available_db_names()
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/worker.py", line 266, in available_db_names
    services = openerp.netsvc.ExportService._services
AttributeError: 'module' object has no attribute 'ExportService'
```

And later it causes crashes when installing xml files  :

```
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/addons/base/res/res_partner.py", line 564, in write
    result = super(res_partner, self).write(vals)
ParseError: "write() takes at least 5 arguments (2 given)" while parsing /home/florent/DEV/Serveurs/odoo/odoo/openerp/addons/base/base_data.xml:23, near
<record id="main_partner" model="res.partner" context="{'default_is_company': True}">
            <field name="name">Your Company</field>
            <field name="company_id" eval="None"/>
            <field name="image" eval="False"/>
            <field name="customer" eval="False"/>
            <field name="is_company" eval="True"/>
            <field name="street"/>
            <field name="city"/>
            <field name="zip"/>
            <field name="phone"/>
            <field name="email">info@yourcompany.com</field>
            <field name="website">www.yourcompany.com</field>
        </record>
```

Not referencing the OCA connector repo don't causes any problem.

Regards

**Comment by guewen** [comment]
We won't maintain the 2.2.0 version, a lot of things have been fixed after it and you should use the most recent version. Consider upgrading connector-prestashop to the last version of the connector.

**Comment by flotho** [comment]
Hi @guewen 
You're right, additionnaly, I found a commit that works for https://github.com/OCA/connector-prestashop/pull/11.
