### ISSUE TITLE
Problem while running un multiprocessing mode

### ISSUE THREAD

**Issue by flotho** [OCA/connector#112]
Hi,

I'm trying to run the connector in the multiprocessing mode following this doc : http://odoo-connector.com/guides/multiprocessing.html
I run on the 3.0 tag
I launch this command from the connector repo folder :

```
PYTHONPATH=/home/florent/DEV/Serveurs/odoo/odoo/openerp connector/openerp-connector-worker --config=/path/to/my/conf/flotho.conf --logfile=/home/florent/myTmp/connector.log --workers=2
```

here is the log of the command, and of course it failed

```
Traceback (most recent call last):
  File "connector/openerp-connector-worker", line 12, in <module>
    import openerp
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/__init__.py", line 98, in <module>
    import cli
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/cli/__init__.py", line 38, in <module>
    import deploy
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/cli/deploy.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 22, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/site-packages/requests/compat.py", line 95, in <module>
    from .packages import chardet
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 20, in <module>
    from queue import LifoQueue, Empty, Full
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/__init__.py", line 22, in <module>
    from . import model
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/model.py", line 30, in <module>
    from .job import STATES, DONE, PENDING, OpenERPJobStorage
  File "/home/florent/DEV/Lib_Odoo/gitMag-OCA-Connector/connector/queue/job.py", line 34, in <module>
    from ..exception import (NotReadableJobError,
ValueError: Attempted relative import beyond toplevel package

```

I'm certainly missing something subtle here but I don't see what,
Could it be a bug

**Comment by flotho** [comment]
Here is a good topic : https://www.odoo.com/fr_FR/forum/help-1/question/how-to-launch-connector-with-multi-worker-49235

**Comment by flotho** [comment]
Solved by referecing absolutely the package

**Comment by sbidoul** [comment]
@flotho if this is a new install, I suggest you try the new job runner: http://odoo-connector.com/guides/jobrunner.html

**Comment by flotho** [comment]
Hi @sbidoul 
Thanks but I'm in the middle of the river because I'm running the PR of @pedrobaeza https://github.com/OCA/connector-prestashop/pull/11 that don't match with the new API, so I have to use old fashion.
BTW, I've already tests the new API and it rocks !

**Comment by pvd276** [comment]
please help me fix it
i have same error
