### ISSUE TITLE
[8.0]Unlink fire when update my server with all addons(-u all)

### ISSUE THREAD

**Issue by faridghanchi** [OCA/connector#149]
Hello all,
I have a production database and connect with Magento and inside the database I have installed connector and its successfully installed and configured as document share by OCA link: http://odoo-magento-connector.com/guides/installation_guide.html#installation.
Product, partner all features are working fine and import/Export. When I have restart the server with <code>./openerp-server --addons-path=addons,magento_addons/connector,magento_addons/connector-ecommerce/,magento_addons/connector-magento/,magento_addons/e-commerce/,magento_addons/product-attribute/,magento_addons/sale-workflow/ -u all -d my_database</code> bellow traceback raise

.........................all my product behave like this first delete and after traceback raise
2015-11-18 11:37:29,906 31356 INFO my_database openerp.addons.base.ir.ir_model: Deleting 2204@product.template (product.product_835)
2015-11-18 11:37:32,639 31356 INFO my_database openerp.addons.base.ir.ir_model: Deleting 2203@product.template (product.product_833)
2015-11-18 11:37:32,712 31356 INFO my_database openerp.addons.base.ir.ir_model: Deleting 2202@product.template (product.product_832)
2015-11-18 11:37:32,836 31356 CRITICAL my_database openerp.service.server: Failed to initialize database `my_database`.
Traceback (most recent call last):
  File "/home/feed/odoo8/openerp/service/server.py", line 924, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/feed/odoo8/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/feed/odoo8/openerp/modules/loading.py", line 382, in load_modules
    registry['ir.model.data']._process_end(cr, SUPERUSER_ID, processed_modules)
  File "/home/feed/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/feed/odoo8/openerp/addons/base/ir/ir_model.py", line 1254, in _process_end
    self.pool[model].unlink(cr, uid, [res_id], context=context)
  File "/home/feed/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/feed/odoo8/addons/mail/mail_thread.py", line 449, in unlink
    res = super(mail_thread, self).unlink(cr, uid, ids, context=context)
  File "/home/feed/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/feed/odoo8/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/feed/odoo8/magento_addons/connector/connector/producer.py", line 86, in unlink
    return unlink_original(self)
  File "/home/feed/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/feed/odoo8/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/feed/odoo8/openerp/models.py", line 3617, in unlink
    'where id IN %s', (sub_ids,))
  File "/home/feed/odoo8/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/feed/odoo8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: update or delete on table "product_product" violates foreign key constraint "account_invoice_line_product_id_fkey" on table "account_invoice_line"
DETAIL:  Key (id)=(1577) is still referenced from table "account_invoice_line".

2015-11-18 11:37:32,853 31356 INFO my_database openerp.modules.loading: loading 1 modules...

I have find some code, unlink method was fire in file path: connector/connector/producer.py

Please give me solution, Is there any configuration issue or another?

**Comment by guewen** [comment]
`on_record_unlink` is indeed triggered as records are deleted. This is the expected behavior.

Your issue is that some XMLIds have been assigned to the module `product` (`product.product_835`, `product.product_833`, ...). When Odoo upgrades the modules, it sees that the `product` addon that not contains any XML record with theses XMLIds so it deletes them (it thinks they have been removed from the addon). As a matter of rule, you should never ever create XMLIds with the name of an addons as prefix. You should correct that by changing the name of the `module` in `ir_model_data` for the product you inserted with a wrong XMLId.

I close this issue which is not an issue of this addon.
