### ISSUE TITLE
'could not serialize access due to concurrent update' error on postpone

### ISSUE THREAD

**Issue by guewen** [OCA/connector#161]
I regularly have errors such as:

```
Traceback (most recent call last):
  File "/home/gbaconnier/customers/xxx/dev/parts/connector/connector/controllers/main.py", line 99, in runjob
    retry_postpone(job, unicode(err), seconds=PG_RETRY)
  File "/home/gbaconnier/customers/xxx/dev/parts/connector/connector/controllers/main.py", line 83, in retry_postpone
    self.job_storage_class(session).store(job)
  File "/home/gbaconnier/customers/xxx/dev/parts/connector/connector/queue/job.py", line 200, in store
    db_record.write(vals)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/connector/connector/queue/model.py", line 152, in write
    res = super(QueueJob, self).write(vals)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/connector/connector/producer.py", line 62, in write
    result = write_original(self, vals)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/models.py", line 3787, in write
    self._write(old_vals)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/models.py", line 3898, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gbaconnier/customers/xxx/dev/parts/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

```

And I don't think I had such errors previously. I wonder if it could come from the recent changes in the jobrunner (https://github.com/OCA/connector/blob/8.0/connector/jobrunner/runner.py#L137-L145) but didn't investigated.

**Comment by guewen** [comment]
Could be due to some instrumentation code I put locally.

**Comment by florian-dacosta** [comment]
Hello @guewen 
I have the same problem, for an odoo in version 8. I wonder if you have solved your problem and if it is the case, what caused this issue?
I got the error very rarely, considering the big number of jobs created on this database, but I have it for different function/canals. 
If you have any tip/idea about it, I apreciate it!

The error : 
Traceback (most recent call last):
  File "/workspace/parts/connector/connector/controllers/main.py", line 98, in runjob
    seconds=PG_RETRY)
  File "/workspace/parts/connector/connector/controllers/main.py", line 81, in retry_postpone
    self.job_storage_class(session).store(job)
  File "/workspace/parts/connector/connector/queue/job.py", line 200, in store
    db_record.write(vals)
  File "/workspace/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/workspace/parts/connector/connector/queue/model.py", line 152, in write
    res = super(QueueJob, self).write(vals)
  File "/workspace/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/workspace/parts/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/workspace/parts/odoo/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/workspace/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/workspace/parts/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/workspace/parts/connector/connector/producer.py", line 62, in write
    result = write_original(self, vals)
  File "/workspace/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/workspace/parts/odoo/openerp/models.py", line 3810, in write
    self._write(old_vals)
  File "/workspace/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/workspace/parts/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/workspace/parts/odoo/openerp/models.py", line 3927, in _write
    cr.execute(query, params + (sub_ids,))
  File "/workspace/parts/odoo/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/workspace/parts/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
  File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/database_psycopg2.py", line 35, in execute
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/newrelic/hooks/database_dbapi2.py", line 25, in execute
    *args, **kwargs)
TransactionRollbackError: could not serialize access due to concurrent update

**Comment by guewen** [comment]
In my case it was only in my dev instance and I had some local changes IIRC.
