### ISSUE TITLE
Binder & Polymorphic Inherits vs. Postgres

### ISSUE THREAD

**Issue by lasley** [OCA/connector#209]
I'm running into an issue with a custom binder, but we're using the same logic in the generic one so I wanted to bring it up here. If someone has some sort of strategy or something to point me in a direction other than straight SQL, the fix will most definitely make its way here 😄 

This edge case comes into play when you create a Bind model on an already polymorphically inherited model. Specifically, we are running into the >63 char limitation on Postgres cols.

Example:

``` python
class MedicalPatientMedication(models.Model):
    _name = 'medical.patient.medication'
    _inherit = ['abstract.medical.medication', 'medical.medication.template']


class MedicalPrescriptionOrderLine(models.Model):
    _name = 'medical.prescription.order.line'
    _inherit = ['abstract.medical.medication']
    _inherits = {'medical.patient.medication': 'medical_medication_id'}
    medical_medication_id = fields.Many2one(
        comodel_name='medical.patient.medication',
        string='Medication',
        required=True, 
        ondelete='cascade',
    )
    carepoint_bind_ids = fields.One2many(
        comodel_name='carepoint.medical.prescription.order.line',
        inverse_name='odoo_id',
        string='Carepoint Bindings',
    )


class CarepointMedicalPrescriptionOrderLine(models.Model):
    _name = 'carepoint.medical.prescription.order.line'
    _inherit = 'carepoint.binding'
    _inherits = {'medical.prescription.order.line': 'odoo_id'}
    odoo_id = fields.Many2one(
        comodel_name='medical.prescription.order.line',
        string='Prescription Line',
        required=True,
        ondelete='cascade'
    )
```

When Binder performs a search in [to_openerp](https://github.com/OCA/connector/blob/9.0/connector/connector.py#L368) or [to_backend](https://github.com/OCA/connector/blob/9.0/connector/connector.py#L397), the following error will be raised from Postgres:

``` bash
2016-09-16 14:29:53,924 18435 INFO test openerp.sql_db: Programming error: missing FROM-clause entry for table "carepoint_medical_prescription_order_line__odoo_id__medical_med"
LINE 1: ...tion_order_line__odoo_id"."medical_medication_id"="carepoint...
                                                             ^
, in query SELECT "carepoint_medical_prescription_order_line".id FROM "medical_patient_medication" as "carepoint_medical_prescription_order_line__odoo_id__me_6877a285","medical_prescription_order_line" as "carepoint_medical_prescription_order_line__odoo_id","carepoint_medical_prescription_order_line" WHERE ("carepoint_medical_prescription_order_line__odoo_id"."medical_medication_id"="carepoint_medical_prescription_order_line__odoo_id__medical_medication_id"."id" AND "carepoint_medical_prescription_order_line"."odoo_id"="carepoint_medical_prescription_order_line__odoo_id"."id") AND ((("carepoint_medical_prescription_order_line__odoo_id__me_6877a285"."active" = %s)  AND  ("carepoint_medical_prescription_order_line"."odoo_id" = %s))  AND  ("carepoint_medical_prescription_order_line"."backend_id" = %s)) ORDER BY "carepoint_medical_prescription_order_line"."id"  
2016-09-16 14:29:53,925 18435 ERROR test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/var/www/odoo/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/www/odoo/openerp/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/var/www/odoo/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/odoo/openerp/http.py", line 313, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/www/odoo/openerp/http.py", line 963, in __call__
    return self.method(*args, **kw)
  File "/var/www/odoo/openerp/http.py", line 513, in response_wrap
    response = f(*args, **kw)
  File "/var/www/odoo/addons/web/controllers/main.py", line 897, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/var/www/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/var/www/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/www/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/www/odoo/addons/mail/models/mail_thread.py", line 233, in create
    thread = super(MailThread, self).create(values)
  File "/var/www/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/sf_dlasley/Documents/Repos/oca-connector/connector/producer.py", line 52, in create
    on_record_create.fire(session, self._name, record_id.id, vals)
  File "/media/sf_dlasley/Documents/Repos/oca-connector/connector/event.py", line 148, in fire
    consumer(*args, **kwargs)
  File "/media/sf_dlasley/Documents/Repos/odoo-connector_carepoint/connector_carepoint/consumer.py", line 73, in delay_create
    bind_record = binder.create_bind(record)
  File "/media/sf_dlasley/Documents/Repos/odoo-connector_carepoint/connector_carepoint/unit/binder.py", line 188, in create_bind
    ('backend_id', '=', self.backend_record.id),
  File "/var/www/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/www/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/var/www/odoo/openerp/models.py", line 1658, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/var/www/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/www/odoo/openerp/models.py", line 4794, in _search
    cr.execute(query_str, where_clause_params)
  File "/var/www/odoo/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/www/odoo/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: missing FROM-clause entry for table "carepoint_medical_prescription_order_line__odoo_id__medical_med"
LINE 1: ...tion_order_line__odoo_id"."medical_medication_id"="carepoint...
```

From what I can tell, there is essentially no way for ORM to use these records - even outside of a standard search. The below can readily replicate this issue with the above model definitions:

``` python
rec = self.env['medical.prescription.order.line'].browse(1)
rec.carepoint_bind_ids
```

Obviously this is an edge case issue created due to the insanely long names in medical, but it is definitely possible elsewhere due to the inheritance strategy of connector being these `_inherits`. It could probably even be considered an Odoo ORM bug.

Honestly I'm stumped & my override in my custom class was just a direct SQL query. I was hoping maybe someone knows a bit more about the polymorphic delegations & could point me in a direction.

I think the solution lies in somehow telling ORM to not retrieve the polymorphic models past the first layer. I spent a while looking over all the ORM code and came up with zilch on that though.

**Comment by lasley** [comment]
Ok yup no fix in sight other than renaming the model. This is bashing against Postgres, so totally out of scope for an Odoo module. Closing
