### ISSUE TITLE
AssertionError: 0 worker found in database instead of 1

### ISSUE THREAD

**Issue by tremlin** [OCA/connector#22]
Today I have encountered a strange timing issue with the connector (Odoo 7, Connector 2.2.0):

2014-09-29 14:24:46,367 4864 ERROR test openerp.service.workers: Worker (4864) Exception occured, exiting...
Traceback (most recent call last):
  File "/srv/openerp/odoo/openerp/service/workers.py", line 307, in run
    self.process_work()
  File "/srv/openerp/addons/addons-external/connector/openerp-connector-worker", line 92, in process_work
    self._work_database(cr)
  File "/srv/openerp/addons/addons-external/connector/openerp-connector-worker", line 73, in _work_database
    max_jobs=MAX_JOBS)
  File "/srv/openerp/addons/addons-external/connector/queue/model.py", line 272, in assign_then_enqueue
    self.enqueue_jobs(cr, uid, context=context)
  File "/srv/openerp/addons/addons-external/connector/queue/model.py", line 297, in enqueue_jobs
    self._enqueue_jobs(cr, uid, context=context)
  File "/srv/openerp/addons/addons-external/connector/queue/model.py", line 350, in _enqueue_jobs
    db_worker_id = self._worker_id(cr, uid, context=context)
  File "/srv/openerp/addons/addons-external/connector/queue/model.py", line 253, in _worker_id
    "of 1" % len(worker_ids))
AssertionError: 0 worker found in database instead of 1

The only thing that I found is the old bug on Launchpad https://bugs.launchpad.net/openerp-connector/+bug/1281073 but this seems to be a different issue because I am running a multiprocessing setup with "--workers=2" on both openerp-server and openerp-connector-worker (and a -d $DBNAME). The problem occurs because _enqueue_jobs is called before _notify_alive but I could not figure out why this is the case. The only strange thing that I noticed is that the connector workers are started in a sleep cycle before going into their first run cycle. This seems to different from other connector installations that I am running successfully.

My solution for now is to surround the line 350 of connector/queue/model.py by try/except:

```
    try:
        db_worker_id = self._worker_id(cr, uid, context=context)
    except Exception:
        return
```

**Comment by tremlin** [comment]
This issue was solved by https://github.com/OCA/connector/pull/24
