### ISSUE TITLE
[8.0] " KeyError: u'product.category,1' " occurs when "Stock Valuation Account" field is changed or left empty

### ISSUE THREAD

**Issue by azeemism** [OCA/connector#239]
Hi,

When `Internal Category > Account Stock Properties > Stock Valuation Account` field is changed or left blank for Internal Category "All" the following error occurs. This does not seem to occur with subcategories or other main categories created.

```
Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/oca80/openerp/http.py", line 544, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/oca80/openerp/http.py", line 581, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/oca80/openerp/http.py", line 317, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/oca80/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/oca80/openerp/http.py", line 314, in checked_call
return self.endpoint(*a, **kw)
File "/opt/odoo/oca80/openerp/http.py", line 810, in __call__
return self.method(*args, **kw)
File "/opt/odoo/oca80/openerp/http.py", line 410, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/oca80/addons/web/controllers/main.py", line 944, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/oca80/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 405, in write
return super(product_category, self).write(cr, uid, ids, vals, context=context)
File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
result = write_original(self, vals)
File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
self._write(old_vals)
File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
File "/opt/odoo/oca80/openerp/models.py", line 3964, in _write
result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
File "/opt/odoo/oca80/openerp/osv/fields.py", line 1485, in set
self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
File "/opt/odoo/oca80/openerp/osv/fields.py", line 1721, in _property_write
ir_property.set_multi(cr, uid, prop_name, obj._name, {id: value}, context=context)
File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/oca80/openerp/api.py", line 372, in old_api
result = method(recs, *args, **kwargs)
File "/opt/odoo/oca80/openerp/addons/base/res/ir_property.py", line 239, in set_multi
id = refs.pop(prop.res_id)
KeyError: u'product.category,1'
```

I was informed that this issue is due to the this module:
`/opt/odoo/oca80/addons-oca/connector/connector/producer.py`

Currently the `Internal Category` `All` is setup as follows:

![image](https://cloud.githubusercontent.com/assets/10731034/24767473/ea8e01b0-1ab3-11e7-9bd7-b6880c46d3e0.png)

I am not sure how `Stock Valuation Account` was populated with `212 OTHER ACCOUNTS PAYABLE` (which is a `View` account). If this field is left blank or changed, the Server Error shown above occurs: `KeyError: u'product.category,1'`

Any assistance in solving this issue would be appreciated.

Thanks for all you do.

**Comment by guewen** [comment]
Hello,

Sorry but you have been badly informed. The `connector` module does not have any effect on the data at this level.

This is more likely to be a misconfiguration of a "Property" in configuration settings. Probably what happened is that you have a property pointing to `product.category,1` which you deleted. You should correct the property.
