### ISSUE TITLE
[10.0] Components Events installation Error

### ISSUE THREAD

**Issue by rmorant** [OCA/connector#263]
Odoo 10.0-20170405 (Community Edition)

After install 'component', without problems, try to install component_event but 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 167, in load_module_graph
    module.with_context(overwrite=overwrite).update_translations()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 767, in update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_translation.py", line 704, in load_module_terms
    res_lang.load_lang(lang)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/res/res_lang.py", line 90, in load_lang
    language.write({'active': True})
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/res/res_lang.py", line 230, in write
    return super(Lang, self).write(vals)
  File "/opt/odoo10/addons/component_event/models/base.py", line 102, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/opt/odoo10/addons/component_event/models/base.py", line 88, in _event
    collecter = work._component_class_by_name('base.event.collecter')(work)
  File "/opt/odoo10/addons/component/core.py", line 290, in _component_class_by_name
    raise NoComponentError("No component with name '%s' found." % name)
NoComponentError: No component with name 'base.event.collecter' found.
```
Thanks in advance

**Comment by sudotrin** [comment]
I had the same issue. It was due to my having the wrong version of cachetools installed by pip. I removed with uninstall, downloaded cachetools-2.0.1 from here https://pypi.python.org/pypi/cachetools and it worked.

**Comment by lasley** [comment]
REF OCA/maintainer-quality-tools#494

**Comment by sbidoul** [comment]
What is the minimum required version of cachetools? Assuming it's `>=2.0.1`, the adding `install_requires=['cachetools>=2.0.1']` to `component`'s [`setup.py`](https://github.com/OCA/connector/blob/10.0/setup/component/setup.py) is a good way to express this.

cc/ @lasley

**Comment by bozaka** [comment]
I have the same problem with connector, I use cachetools 2.0.1. I work in Odoo 10 Enterprise
How to fix it ? Thanks

**Comment by guewen** [comment]
I think the minimum required is >=2.0.0 but as 2.0.1 brings support of python 3.6, we could use >=2.0.1

**Comment by hburbano** [comment]
Using Odoo Comunity (10.0-20171030) having the exact same problem even though I have installed cachetools 2.0.1 (both from pip install and pypi download) any idea?

**Comment by lasley** [comment]
@Nslaver - hmmm I think this has to be a setup issue at this point. I can install and remove all connector modules on Runbot, which is built directly from our `requirements` files. It's also working perfectly on multiple production servers on my end, also built directly from the requirements definitions.

I would look for errors in your log after rebooting Odoo and retrying the module installation - those typically hold clues as to why a module is failing. Short of new info being provided though, I'm closing this issue as environment related.
