### ISSUE TITLE
Odoo 11.0 Components Events Installation Problem

### ISSUE THREAD

**Issue by berkcirisci** [OCA/connector#279]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 167, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 865, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_translation.py", line 706, in load_module_terms
    res_lang.load_lang(lang)
  File "/opt/odoo/odoo/odoo/addons/base/res/res_lang.py", line 90, in load_lang
    language.write({'active': True})
  File "/opt/odoo/odoo/odoo/addons/base/res/res_lang.py", line 225, in write
    res = super(Lang, self).write(vals)
  File "/opt/odoo/addons/connector/component_event/models/base.py", line 103, in write
    self._event('on_record_write').notify(record, fields=fields)
  File "/opt/odoo/addons/connector/component_event/models/base.py", line 88, in _event
    collecter = work._component_class_by_name('base.event.collecter')(work)
  File "/opt/odoo/addons/connector/component/core.py", line 290, in _component_class_by_name
    raise NoComponentError("No component with name '%s' found." % name)
odoo.addons.component.exception.NoComponentError: No component with name 'base.event.collecter' found.

I have installed component and also i have installed cache tools 2.0.1 but still I am having this problem. Thank you for your responses

**Comment by guewen** [comment]
Could you give more information about your setup? What is the odoo version, what is the git revision you are using?

**Comment by berkcirisci** [comment]
I am using Ubuntu 16.04 from virtual machine and I installed it with
$git clone https://www.github.com/odoo/odoo --depth 1 --branch 11.0 --single-branch
with using the guidance of this site:
https://www.getopenerp.com/install-odoo-11-on-ubuntu-16-04/

I can provide more information if you need. Thank you in advance

**Comment by lgarcia11** [comment]
@berkcirisci I am having the same issue, did you found any solution? Thanks

**Comment by AttentionalM** [comment]
revision bf2af719903eec3e1ec1d8b8ee3aa682d83070c0 
Same issue whilst installing component_event here on CE 11.0 also from git on Oracle Enterprise Linux 7.4. Oddly I can get it to pass test_component_collection.py and test_components.py from the command line.

**Comment by okmuk** [comment]
Same here. Exactly as reported by berkcirisci

**Comment by guewen** [comment]
What version of Python do you use?

**Comment by okmuk** [comment]
Python version 3.5.2 on Ubuntu server 16.04 LTS. Odoo 11 does not support Python v 2.7

**Comment by lgarcia11** [comment]
@guewen in my case is happening for Python 3.6 64 bit on WIndows 10.
It's also not working in the official runbot for this repo.

**Comment by guewen** [comment]
The runbot seems to work: https://runbot.odoo-community.org/runbot/repo/github-com-oca-connector-102

There is a running db at this moment: http://3320278-11-0-bf2af7.runbot2.odoo-community.org

**Comment by guewen** [comment]
@okmuk are you on windows as well?

**Comment by okmuk** [comment]
Ubuntu server 16.04 LTS

**Comment by lgarcia11** [comment]
The runbot is installed and seems to be working,
but if you uninstall the module in that runbot when trying to install it back is throwing the same error as reported here.

**Comment by okmuk** [comment]
If it helps. Placing

        if model_name.startswith('res.') or model_name.startswith('ir.'):
            return CollectedEvents([])

between lines 79 and 80 here https://github.com/OCA/connector/blob/11.0/component_event/models/base.py, removes the issue. Not sure if permanently and does not create some other one.

**Comment by guewen** [comment]
Couldn't reproduce on runbot by uninstalling / reinstalling.
Is it only when you have more than one database? Is it only after an uninstall / reinstall, only with install from the UI? Does it happen when you install the addon with the `-i` option?

**Comment by guewen** [comment]
I finally could reproduce it on runbot

**Comment by guewen** [comment]
> Not sure if permanently and does not create some other one.

This fix will prevent to have events on `ir.*` and `res.*` models.

**Comment by guewen** [comment]
Please check #283, note that using `-i` for installing the module should work as a workaround.

**Comment by janarthanandev** [comment]
we are also facing this issue while importing data. 

> self.backend_adapter.read(self.external_id)

Error 
NoComponentError: No component found for collection 'abc.backend', usage 'backend.adapter', model_name 'abc.stock.picking'. 

Please help me what we are missing
