### ISSUE TITLE
NoComponentError: No component found for collection 'abc.backend', usage 'backend.adapter', model_name 'abc.stock.picking'.  

### ISSUE THREAD

**Issue by janarthanandev** [OCA/connector#314]
we are facing this issue while importing data.
**Our Code**
core.py
```
class SmartWarehouseConnectorComponent(AbstractComponent):
    _name = 'base.abc.connector'
    _inherit = 'base.connector'
    _collection = 'abc.backend'
```
We have created component for 
backend_adapter.py
```
class AbcCRUDAdapter(AbstractComponent):
    _name = 'abc.crud.adapter'
    _inherit = ['base.backend.adapter', 'base.abc.connector']
    _usage = 'backend.adapter'
```

In binding.py
```
class AbcBinding(models.AbstractModel):
    _name = 'abc.binding'
    _inherit = 'external.binding'
    _description = 'Abc Binding (abstract)'

    @job(default_channel='root.abc')
    @api.model
    def import_record(self, backend, external_id, force=False):
           with backend.work_on(self._name) as work:
               importer = work.component(usage='record.importer')
          return importer.run(external_id, force=force)
```

In backend
```
class AbcBackend(models.Model):
    _name = 'abc.backend'
    _inherit = 'connector.backend'
    
    @api.multi
    def import_pickings(self):
       for backend in self:
           self.env['abc.stock.picking'].with_delay().import_batch(backend)
       return True

```
importer.py
```
class AbcImporter(AbstractComponent):
    _name = 'abc.importer'
    _inherit = ['base.importer', 'base.abc.connector']
    _usage = 'record.importer'
    
    
    def _get_abc_data(self):
        return self.backend_adapter.read(self.external_id) 
```
#Error raised in this line it does not looking into CRUD Adapter it checking in synchronization and throwing NOComponentError

**Exception Information**
--
Traceback (most recent call last): File "/opt/odoo/testing/community_modules_links/queue_job/controllers/main.py", line 97, in runjob self._try_perform_job(env, job) File "/opt/odoo/testing/community_modules_links/queue_job/controllers/main.py", line 61, in _try_perform_job job.perform() File "/opt/odoo/testing/community_modules_links/queue_job/job.py", line 367, in perform self.result = self.func(*tuple(self.args), **self.kwargs) File "/opt/odoo/testing/community_modules_links/connector_abc/models/smartwarehouse_binding/common.py", line 52, in import_record return importer.run(external_id, force=force) File "/opt/odoo/testing/community_modules_links/connector_abc/components/importer.py", line 182, in run self.sw_record = self._get_sw_data() File "/opt/odoo/testing/community_modules_links/connector_abc/components/importer.py", line 30, in _get_sw_data return self.backend_adapter.read(self.external_id) File "/opt/odoo/testing/community_modules/connector/connector/components/synchronizer.py", line 89, in backend_adapter usage=self._base_backend_adapter_usage File "/opt/odoo/testing/community_modules/connector/component/core.py", line 709, in component return self.work.component(usage=usage, model_name=model_name) File "/opt/odoo/testing/community_modules/connector/component/core.py", line 385, in component (self.collection._name, usage, model_name) odoo.addons.component.exception.NoComponentError: No component found for collection 'abc.backend', usage 'backend.adapter', model_name 'abc.stock.picking'. |  

Hope we are missing something please help in this issue. Thanks in Advance.

**Comment by guewen** [comment]
AbcCRUDAdapter is abstract, declare it as a Component otherwise it's not meant to be used / retrieved

**Comment by janarthanandev** [comment]
Thanks for your quick reply @guewen :-) . It working now thank you so much

**Comment by guewen** [comment]
Great :)
