### ISSUE TITLE
models are not correctly stored in the database (v11.0)

### ISSUE THREAD

**Issue by lalibrerie-solidaire** [OCA/connector#321]
Hello,

I’m trying to build a connector between Odoo and Trello, based on the Odoo connector v11.0. I downloaded the connector source code and installed it. I had no problem to install the module, but it seems some models build in the module are not registered in the database.

In my case, I can’t inherits from 'base.backend.adapter.crud', I get this error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 938, in
call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 926, in
_call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 71, in
check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 449, in
button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 542, in
_button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status,
update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 274, in
load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 146, in
load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 250, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/odoo/odoo/models.py", line 447, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." %
(name, parent))
TypeError: Model 'trello.backend.adapter.crud' inherits from
non-existing model 'base.backend.adapter.crud'.

I checked in Settings | Technical | Database Structure | Models menu
and, indeed, the model does not appear in the list, even though it is
the source code and I checked that the file, in which the model is
defined, is called in the __init__.py `file.

It seems some models are not correctly stored in the database, while
some others, such as 'connector.backend' are and causes no inheritance
issues.

I would like some info on what could the problem be and what could fix it.

Thank you.

**Comment by guewen** [comment]
You are confusing models and components. Classes that inherit Component are not models and not stored in the database. They are neither in the odoo registry but are registered with a backend.
A model cannot inherit a component and the component cannot inherit a model.

**Comment by lalibrerie-solidaire** [comment]
Ok, I did not know that, so I made my class inherit from AbstractComponent, instead of models.Model and it solved the issue. 
Thank you
