### ISSUE TITLE
Connector installation :  NameError: name 'cachedmethod' is not defined

### ISSUE THREAD

**Issue by EngiSouha** [OCA/connector#324]
I'm trying to install  this connector [https://apps.odoo.com/apps/modules/11.0/connector/](url)  on odoo v11 but it's throwing the following error below  , I tried this : pip install cachetools  , but in vain the same error still appeared . any solutions please ?

---------------------------------------------------------------------------------------------------------------------------
2019-02-22 13:17:32,665 14876 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/dell/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/dell/PycharmProjects/odoo11/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/home/dell/PycharmProjects/odoo11/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/dell/PycharmProjects/odoo11/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/dell/PycharmProjects/odoo11/odoo/http.py", line 1318, in __call__
    self.load_addons()
  File "/home/dell/PycharmProjects/odoo11/odoo/http.py", line 1350, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
    
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
    
  File "/home/dell/PycharmProjects/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 2, in <module>
    
  File "/home/dell/PycharmProjects/odoo11/addons/connector/components/__init__.py", line 2, in <module>
    from . import core
  File "/home/dell/PycharmProjects/odoo11/addons/connector/components/core.py", line 72, in <module>
    from odoo.addons.component.core import AbstractComponent
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
    
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
    
  File "/home/dell/PycharmProjects/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 2, in <module>
    
  File "/home/dell/PycharmProjects/odoo11/addons/component/core.py", line 66, in <module>
    class ComponentRegistry(object):
  File "/home/dell/PycharmProjects/odoo11/addons/component/core.py", line 107, in ComponentRegistry
    @cachedmethod(operator.attrgetter('_cache'))
NameError: name 'cachedmethod' is not defined

**Comment by rvalyi** [comment]
Hello @EngiSouha. I had the same issue when I was using the wrong 
cachetools version. Make sure you have 
cachetools>=2.0.1,<3.0.0 as specified in the OCA requirements.txt for instance:
https://github.com/OCA/connector/blob/11.0/requirements.txt

Can you confirm this fixes the problem?

**Comment by EngiSouha** [comment]
@rvalyi  thanks for replying , actually I have the same version of cachetools but yet still the same error , by the way I'm using python 3.6 , when i tried installing cachetools :  
in the first time by typing :  sudo apt-get install python-cachetools 
-----------------------------------------------
dell@dell:~$ sudo apt-get install python-cachetools 
[sudo] password for dell: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-cachetools is already the newest version (2.0.0-2).
The following packages were automatically installed and are no longer required:
  libatkmm-1.6-1v5 libcairomm-1.0-1v5 libgtkmm-3.0-1v5 libnih-dbus1
  libpangomm-1.4-1v5 python-apt python-pycurl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
 ----------------------------------------------------

and when I type this one : pip install cachetools 
---------------------------------------
dell@dell:~$ pip install cachetools
Collecting cachetools
  Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Installing collected packages: cachetools
Successfully installed cachetools-3.1.0


I'm confused I don't know what to do exactly .please if you have any other solution let me know  I'll be thankfull to you.

**Comment by EngiSouha** [comment]
@rvalyi  thank you so much. I solved the problem by this : pip3 install -r requirements.txt ,        
I was installing the cachetools in the wrong path .

----------------------------------SOLUTION---------------------------------------
dell@dell:~/PycharmProjects/odoo11/addons$ pip3 install -r requirements.txt
Collecting cachetools<3.0.0,>=2.0.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Installing collected packages: cachetools
Successfully installed cachetools-2.1.0
