### ISSUE TITLE
ValueError en external_id field when calling binder.to_internal() function

### ISSUE THREAD

**Issue by lalibrerie-solidaire** [OCA/connector#328]
Hi,

I’m trying to implement a connector, using the connector framework in Odoo 11.0. I built a backend model:

```
class TrelloBackend(models.Model):
    _name='trello.backend'
    _description='Trello Backend'
    _inherit='connector.backend'

    name = fields.Char('Backend name')

    @api.multi
    def read_projects(self, client):
        #only one backend record is needed
        logging.debug("current user name: {}".format(self.env.user.name))
        set_card = self.search_count([])
        logging.debug("backends cardinality: {}".format(set_card))

        if set_card == 0:
            set_card = set_card + 1
            logging.debug("creating backend: trello backend {}".format(set_card))
            self.create({
                'name': 'trello backend {}'.format(set_card),
                'create_date': datetime.datetime.now()
                })

        #getting newly created backend
        backend = self.search([('name','=','trello backend {}'.format(set_card))])
        logging.debug(backend.__repr__())

        with backend.work_on(model_name='trello.backend') as work:
            adapter = work.component(usage='backend.adapter')
            binder = work.component(usage='project.binder')
            projects = self.env['project.project']
            work.projects_data = adapter.read(client=client)

            for project_data in work.projects_data:
                new_project = projects.create({
                    'name': project_data.name,
                    'board_url': project_data.url,
                    'desc': project_data.description,
                })

                binder.bind(external_id=project_data.id, binding=new_project.id)

            logging.debug("getting binder data")
            b_1 = binder.to_internal(project_data.id, unwrap=False)
            b_2 = binder.to_internal(project_data.id, unwrap=True)

            logging.debug("bindings for unwrap False: {}".format(b_1.__repr__()))
            logging.debug("bindings for unwrap True: {}".format(b_2.__repr__()))

            #temporary, to be removed later
            for project_data in work.projects_data:
                p = projects.search([('name','=',project_data.name),
                                     ('board_url','=',project_data.url)])
                p.unlink()
```

Then, I extended the project model, form the Project application :

```
class TrelloProject(models.Model):
    _inherit='project.project'

    desc=fields.Text('Description')
    board_url=fields.Text('Trello Board URL',readonly=True)

    @api.model
    def import_projects(self):
        client = self.env.user.get_trello_client()
        self.env['trello.backend'].read_projects(client=client)
```

And a binder, divided into an abstract model and a concrete model:

```
class TrelloAbstractBinder(AbstractComponent):
    _name='trello.abstract.binder'
    _inherit='base.binder'

    external_id=fields.Char('ID dans Trello')
    sync_date=fields.Datetime('Last sync date')
    backend_id=fields.Many2one('trello.backend')

```
```
class TrelloProjectBinder(Component):
    _name='trello.project.binder'
    _inherit='trello.abstract.binder'
    _usage = 'project.binder'

    odoo_id = fields.Many2one('project.project')
```

Now, I’m trying to understand how to use the binder object, to check if a project imported from an external sources already have a corresponding record in odoo.

So, in the backend model, I added those lines:

```
            logging.debug("getting binder data")
            b_1 = binder.to_internal(project_data.id, unwrap=False)
            b_2 = binder.to_internal(project_data.id, unwrap=True)

            logging.debug("bindings for unwrap False: {}".format(b_1.__repr__()))
            logging.debug("bindings for unwrap True: {}".format(b_2.__repr__()))
```

to check and understand the binders behavior and data format. But, when I use the fonction, I get the following error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/cyrille/odoo/addons-dev/connector_trello/models/trello_project.py", line 16, in import_projects
    self.env['trello.backend'].read_projects(client=client)
  File "/home/cyrille/odoo/addons-dev/connector_trello/models/trello_backend.py", line 56, in read_projects
    b_1 = binder.to_internal(project_data.id, unwrap=False)
  File "/home/cyrille/odoo/addons-ext/connector/components/binder.py", line 53, in to_internal
    (self._backend_field, '=', self.backend_record.id)]
  File "/opt/odoo/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/odoo/models.py", line 3773, in _search
    query = self._where_calc(args)
  File "/opt/odoo/odoo/odoo/models.py", line 3563, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/odoo/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/opt/odoo/odoo/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'external_id' in leaf "<osv.ExtendedLeaf: ('external_id', '=', '5c050deee03b0c1925c3204a') on trello_backend (ctx: )>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1231, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 554, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_actions.py", line 430, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/cyrille/odoo/addons-dev/connector_trello/models/trello_project.py", line 16, in import_projects
    self.env['trello.backend'].read_projects(client=client)
  File "/home/cyrille/odoo/addons-dev/connector_trello/models/trello_backend.py", line 56, in read_projects
    b_1 = binder.to_internal(project_data.id, unwrap=False)
  File "/home/cyrille/odoo/addons-ext/connector/components/binder.py", line 53, in to_internal
    (self._backend_field, '=', self.backend_record.id)]
  File "/opt/odoo/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo/odoo/models.py", line 3773, in _search
    query = self._where_calc(args)
  File "/opt/odoo/odoo/odoo/models.py", line 3563, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/odoo/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/opt/odoo/odoo/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: <class 'ValueError'>: "Invalid field 'external_id' in leaf "<osv.ExtendedLeaf: ('external_id', '=', '5c050deee03b0c1925c3204a') on trello_backend (ctx: )>"" while evaluating
"env['project.project'].import_projects()"
```

and I can’t figure out, what’s wrong with the external_id field. It is defined in the abstract binder model (`external_id=fields.Char('ID dans Trello')`) and the concrete binder inherits from it (`_inherit='trello.abstract.binder'`).

Thanks for your attention.

**Comment by guewen** [comment]
Here:

```python
class TrelloAbstractBinder(AbstractComponent):
    _name='trello.abstract.binder'
    _inherit='base.binder'

    external_id=fields.Char('ID dans Trello')
    sync_date=fields.Datetime('Last sync date')
    backend_id=fields.Many2one('trello.backend')

class TrelloProjectBinder(Component):
    _name='trello.project.binder'
    _inherit='trello.abstract.binder'
    _usage = 'project.binder'

    odoo_id = fields.Many2one('project.project')
```

You cannot declare fields in Component classes. Either they are Models and stored in database, either they are Components and only contains logic. `Binder` is the Component to bind / search bindings. A Binding is a Model which actually store the external id.
