### ISSUE TITLE
[12.0] No component registry for database db. Probably because the Odoo registry has not been built yet. 

### ISSUE THREAD

**Issue by hparfr** [OCA/connector#395]
Hi,

I have this kind of errors in a near empty database few seconds after boot.
```
  File "/odoo/links/base_rest/models/rest_service_registration.py", line 100, in _get_services
    model_name="rest.service.registration", collection=collection
  File "/odoo/links/component/core.py", line 248, in __init__
    self.components_registry = _component_databases[dbname]
KeyError: 'db'
```

. _component_databases is empty. odoo v12

Any ideas ?

**Comment by guewen** [comment]
In what context? In a test or normal runtime?

**Comment by guewen** [comment]
It could be related to the initialization of the components registry in base_rest: https://github.com/OCA/rest-framework/blob/abd74cd7241d3b93054825cc3e41cb7b693c9000/base_rest/models/rest_service_registration.py#L47-L69

We had such kind of issues with component events and added a ready flag on the component registry to avoid such errors: https://github.com/OCA/connector/commit/169043cbed410cb84f43aec68ad3b438b13e76bd
But it doesn't seem related to this as `_get_services` in `base_rest` is called only by the `_register_hook`.

**Comment by hparfr** [comment]
In a dev environment, normal runtime, with up to date dependencies and a fresh db from this morning.
It happens randomly during odoo initialization, like a race condition, and when it happens the server can't handle any request.

Will continue to investigate

**Comment by hparfr** [comment]
Updated python version and the issue is gone.

(was based on camptocamp/odoo-project:12.0-latest , now with camptocamp/odoo-project:14.0-latest it works, still odoo v12)

**Comment by rvalyi** [comment]
Hello,

For the record I had the same issue with EOL Python 3.5 from camptocamp/odoo-project:12.0-latest
But moving to camptocamp/odoo-project:12.0-buster-latest (Python 3.7.3) **fixed the issue**. 

My stack trace was:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/odoo/src/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/odoo/src/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/src/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/src/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/odoo/src/odoo/http.py", line 1456, in dispatch
    request = self.get_request(httprequest)
  File "/odoo/external-src/rest-framework/base_rest/http.py", line 213, in get_request
    odoo.registry(db)
  File "/odoo/src/odoo/__init__.py", line 117, in registry
    return modules.registry.Registry(database_name)
  File "/odoo/src/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/odoo/src/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 529, in load_modules
    model._register_hook()
  File "/odoo/external-src/rest-framework/base_rest/models/rest_service_registration.py", line 64, in _register_hook
    self._build_controllers_routes(services_registry)
  File "/odoo/external-src/rest-framework/base_rest/models/rest_service_registration.py", line 68, in _build_controllers_routes
    for service in self._get_services(controller_def["collection_name"]):
  File "/odoo/external-src/rest-framework/base_rest/models/rest_service_registration.py", line 100, in _get_services
    model_name="rest.service.registration", collection=collection
  File "/odoo/external-src/connector/component/core.py", line 247, in __init__
    self.components_registry = _component_databases[dbname]
KeyError: 'db' - - -
```

**Comment by kevinkhao** [comment]
I am having the same on 3.7.3

**Comment by kevinkhao** [comment]
After further investigation: it seems wrong version of SavepointCase was used.
