### ISSUE TITLE
Possible cache issue w/ component_event when using queue_job

### ISSUE THREAD

**Issue by simahawk** [OCA/connector#411]
Versions:
- component 13.0.1.2.0
- component_event 13.0.1.1.0
- cachetools 2.1.0

I'm experiencing this weird issue (only locally for now)

```
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:8069/queue_job/runjob?db=odoodb&job_uuid=b308b2c9-752f-437f-b935-e8d3554b28cd
2021-08-10 09:14:44,379 1 ERROR odoodb werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo/external-src/queue/queue_job/controllers/main.py", line 73, in runjob
    self._try_perform_job(env, job)
  File "/odoo/external-src/queue/queue_job/controllers/main.py", line 28, in _try_perform_job
    job.store()
  File "/odoo/external-src/queue/queue_job/job.py", line 539, in store
    self._store_values()
  File "/odoo/external-src/queue/queue_job/models/queue_job.py", line 160, in write
    result = super().write(vals)
  File "/odoo/src/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/odoo/src/addons/mail/models/mail_activity.py", line 726, in write
    return super(MailActivityMixin, self).write(vals)
  File "/odoo/external-src/connector/component_event/models/base.py", line 112, in write
    self._event("on_record_write").notify(record, fields=fields)
  File "/odoo/external-src/connector/component_event/models/base.py", line 98, in _event
    return collecter.collect_events(name)
  File "/odoo/external-src/connector/component_event/components/event.py", line 262, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/odoo/external-src/connector/component_event/components/event.py", line 234, in _collect_events
    return self._collect_events_cached(collection_name, self.work.model_name, name)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/__init__.py", line 89, in wrapper
    c[k] = v
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 21, in __setitem__
    cache_setitem(self, key, value)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/cache.py", line 62, in __setitem__
    self.popitem()
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 35, in popitem
    return (key, self.pop(key))
  File "/usr/local/lib/python3.7/dist-packages/cachetools/abc.py", line 35, in pop
    raise KeyError(key)
KeyError: (Component(base.event.collecter), None, 'queue.job', 'on_record_create')
```
It seems that the event collector is looking up for key that it's not there and that should not even be looked for.
In this case we get a write on a queue.job record and it looks up for `on_record_create`. 
Makes no sense to me. 

The key error could come from any model (eg: yesterday I saw it for rest.log but there was no REST request happening).
Here you see another random example in shopinvader context:
```
021-08-04 11:49:34,769 1 INFO odoodb werkzeug: 127.0.0.1 - - [04/Aug/2021 11:49:34] "GET /queue_job/runjob?db=odoodb&job_uuid=723f0b7a-0d62-48f5-8886-1d207ff74f78 HTTP/1.1" 500 - 197 14.115 48.540
2021-08-04 11:49:34,782 1 ERROR odoodb werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo/external-src/queue/queue_job/controllers/main.py", line 73, in runjob
    self._try_perform_job(env, job)
  File "/odoo/external-src/queue/queue_job/controllers/main.py", line 32, in _try_perform_job
    job.perform()
  File "/odoo/external-src/queue/queue_job/job.py", line 510, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/odoo/external-src/search-engine/connector_search_engine/models/se_index.py", line 147, in batch_export
    {"sync_state": "scheduled"}
  File "/odoo/external-src/odoo-shopinvader/shopinvader/models/shopinvader_variant.py", line 126, in write
    result = super(ShopinvaderVariant, self).write(vals)
  File "/odoo/external-src/search-engine/connector_search_engine/models/se_binding.py", line 71, in write
    res = super(SeBinding, self - not_new).write(vals)
  File "/odoo/external-src/connector/component_event/models/base.py", line 112, in write
    self._event("on_record_write").notify(record, fields=fields)
  File "/odoo/external-src/connector/component_event/models/base.py", line 98, in _event
    return collecter.collect_events(name)
  File "/odoo/external-src/connector/component_event/components/event.py", line 262, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/odoo/external-src/connector/component_event/components/event.py", line 234, in _collect_events
    return self._collect_events_cached(collection_name, self.work.model_name, name)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/__init__.py", line 89, in wrapper
    c[k] = v
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 21, in __setitem__
    cache_setitem(self, key, value)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/cache.py", line 62, in __setitem__
    self.popitem()
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 35, in popitem
    return (key, self.pop(key))
  File "/usr/local/lib/python3.7/dist-packages/cachetools/abc.py", line 33, in pop
    del self[key]
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 25, in __delitem__
    cache_delitem(self, key)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/cache.py", line 73, in __delitem__
    del self.__data[key]
KeyError: (Component(base.event.collecter), None, 'shopinvader.variant', 'on_record_write')
```
It's hard to debug because when I restart the cache is flushed and the behavior might get back to normality.
Due to this it might be simply a caching issue whereas `cachetools` tries to delete a key that is not there.
BTW having the component class as a key is not a good idea IMO.

@guewen have you ever seen something similar?

**Comment by simahawk** [comment]
Just reporting another random example that I got today after starting a local instance:
```
2021-08-12 06:50:57,140 1 INFO odoodb odoo.models.unlink: User #1 deleted queue.job records with IDs: [10059892, 10059528, 10059018, 10059017, 10058989, 10058987, 10058984, 10058983, 10058982, 10058981, 10058980, 10058979, 10057418, 10057417, 10057416, 10057415, 10057414, 10057413, 10057412, 9898926, 9898925, 9898817, 9898775, 9894952, 9894951, 9894950, 9894949, 9894948, 9894947, 9894946] 
2021-08-12 06:50:57,193 1 ERROR odoodb odoo.addons.queue_job.controllers.main: Traceback (most recent call last):
  File "/odoo/src/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/odoo/external-src/queue/queue_job/models/queue_job.py", line 261, in autovacuum
    jobs.unlink()
  File "/odoo/src/addons/mail/models/mail_thread.py", line 344, in unlink
    [('res_model', '=', self._name), ('res_id', 'in', self.ids)]
  File "/odoo/src/addons/mail/models/mail_followers.py", line 67, in unlink
    return super(Followers, self).unlink()
  File "/odoo/external-src/connector/component_event/models/base.py", line 117, in unlink
    self._event("on_record_unlink").notify(record)
  File "/odoo/external-src/connector/component_event/models/base.py", line 98, in _event
    return collecter.collect_events(name)
  File "/odoo/external-src/connector/component_event/components/event.py", line 262, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/odoo/external-src/connector/component_event/components/event.py", line 234, in _collect_events
    return self._collect_events_cached(collection_name, self.work.model_name, name)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/__init__.py", line 89, in wrapper
    c[k] = v
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 21, in __setitem__
    cache_setitem(self, key, value)
  File "/usr/local/lib/python3.7/dist-packages/cachetools/cache.py", line 62, in __setitem__
    self.popitem()
  File "/usr/local/lib/python3.7/dist-packages/cachetools/lru.py", line 35, in popitem
    return (key, self.pop(key))
  File "/usr/local/lib/python3.7/dist-packages/cachetools/abc.py", line 35, in pop
    raise KeyError(key)
KeyError: (Component(base.event.collecter), None, 'mail.notification', 'on_record_unlink')
```
