### ISSUE TITLE
[7.0] job runner logging error

### ISSUE THREAD

**Issue by guewen** [OCA/connector#95]
I get the following error on a 7.0 instance with the job runner running in production.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/srv/openerp/parts/server/openerp/netsvc.py", line 154, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/srv/openerp/parts/connector/connector/jobrunner/channels.py", line 369, in __str__
    len(self._failed))
TypeError: %d format: a number is required, not NoneType
Logged from file channels.py, line 458
```

**Comment by guewen** [comment]
Patches proposed on #99 (7.0) and #98 (8.0)
